version: '3'
services:
  web:
    image: books/books-app
    build: ./client/.
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    environment:
      - HOST=0.0.0.0
      - PORT=8080

  api:
    image: books/books-api
    build: ./server/.
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - "8888:8888"
    environment:
      - HOST=0.0.0.0
      - PORT=8888
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_REGION=us-east-1

  admin:
    image: instructure/dynamo-local-admin
    ports:
      - "8001:8001"
    environment:
      - HOST=0.0.0.0
      - PORT=8001
      - AWS_ACCESS_KEY_ID=key
      - AWS_SECRET_ACCESS_KEY=secret
      - AWS_REGION=us-east-1

  dynamodb:
    image: amazon/dynamodb-local:latest
    volumes:
      - ./data:/home/dynamodblocal/data
    ports:
      - "8000:8000"
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-dbPath", "/home/dynamodblocal/data/"]
